## One Sample T-test

###### H0 --- There is no difference between sample mean and population mean.
###### h1 --- There is difference

eg 1.


In [1]:
ages=[21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,45,46,47,48,49,50]

In [2]:
len(ages)

29

In [3]:
import numpy as np
ages_mean=np.mean(ages)
print(ages_mean)

35.206896551724135


## Lets Take Sample

In [4]:
sample_size=14
age_sample=np.random.choice(ages,sample_size)

In [5]:
age_sample

array([41, 26, 37, 23, 49, 33, 41, 35, 21, 28, 36, 33, 49, 22])

In [6]:
age_sample.mean()

33.857142857142854

In [9]:
from scipy.stats import ttest_1samp
ttest,p_value=ttest_1samp(age_sample,35)

In [10]:
print(p_value)

0.6493777231477058


In [11]:
if p_value<0.05:
    print("Reject null hypothesis")
else:
    print("Accept null hypothesis")
    

Accept null hypothesis


eg 2.

# Two Sample T-Test

In [12]:
import scipy.stats as stats


In [13]:
classA_ages=stats.poisson.rvs(loc=18,mu=36,size=60)
classB_ages=stats.poisson.rvs(loc=18,mu=30,size=65)

In [15]:
classA_ages.mean()


54.5

In [16]:
classB_ages.mean()

47.815384615384616

In [18]:
_,P_value=stats.ttest_ind(a=classA_ages,b=classB_ages,equal_var=False)

In [19]:
print(P_value)

6.447176038252191e-09


In [20]:
if p_value<0.05:
    print("Reject Null hypothesis")
else:
    print("Accept Null hypothesis")

Accept Null hypothesis


# Paired T-Test with python

In [24]:
import pandas as pd

In [22]:
weight1=[20,21,22,23,24,25,26,27,28,29,30]
weight2=weight1+stats.norm.rvs(scale=5,loc=1.25,size=11)

In [23]:
print(weight1)
print(weight2)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
[24.02118524 22.11291212 22.57547192 19.94957    34.34290298 21.36320518
 33.44663758 37.76402449 34.00026753 25.16106202 24.58401061]


In [25]:
weight_df=pd.DataFrame({"weight10":np.array(weight1),"weight20":np.array(weight2),
                        "weight_change":np.array(weight2)-np.array(weight1)})

In [26]:
weight_df

weight10   weight20  weight_change
0         20  24.021185       4.021185
1         21  22.112912       1.112912
2         22  22.575472       0.575472
3         23  19.949570      -3.050430
4         24  34.342903      10.342903
5         25  21.363205      -3.636795
6         26  33.446638       7.446638
7         27  37.764024      10.764024
8         28  34.000268       6.000268
9         29  25.161062      -3.838938
10        30  24.584011      -5.415989

In [27]:
_,P_value=stats.ttest_rel(a=weight1,b=weight2)

In [28]:
print(P_value)

0.2402074570921122


In [29]:
if p_value<0.05:
    print("Reject Null hypothesis")
else:
    print("Accept Null hypothesis")

Accept Null hypothesis


# CHI-Square Test

In [31]:
import seaborn as sns
import pandas as pd
import numpy as np
import scipy.stats as stats

In [32]:
dataset=sns.load_dataset("tips")

In [34]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [35]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])

In [36]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [61]:
observed_values=dataset_table.values
print("observed values\n",dataset_table.values)

observed values
 [[60 97]
 [33 54]]


In [39]:
val=stats.chi2_contingency(dataset_table)

In [40]:
val

(0.0,
 1.0,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [41]:
expected_value=val[3]

In [42]:
expected_value

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [54]:
no_rows=len(dataset_table.iloc[0:2,0])
no_rows

2

In [55]:
no_col=len(dataset_table.iloc[0,0:2])
no_col

2

In [56]:
degree_of_freedom=(no_rows-1)*(no_col-1)

In [57]:
degree_of_freedom

1

In [62]:
chi_square=sum([(o-e)**2/e for o,e in zip(observed_values,expected_value)])

In [63]:
print(chi_square)

[0.00119737 0.00073745]


In [64]:
chi_square_statistic=chi_square[0]+chi_square[1]

In [65]:
print(chi_square_statistic)

0.001934818536627623


In [67]:
alpha=0.05
critical_value=stats.chi2.ppf(q=1-alpha,df=degree_of_freedom)
print("critical_value",critical_value)

critical_value 3.841458820694124


In [69]:
if chi_square_statistic>=critical_value:
    print("reject null hypothesis, there is a relationship between 2 categorical variables")
else:
    print("accept null hypothesis, there is no relationship between 2 categorical variables")

accept null hypothesis, there is no relationship between 2 categorical variables


## p value

In [68]:
p_value=1-stats.chi2.cdf(x=chi_square_statistic,df=degree_of_freedom)
print("p-value",p_value)

p-value 0.964915107315732


In [71]:
if p_value<=alpha:
    print("reject null hypothesis, there is a relationship between 2 categorical variables")
else:
    print("accept null hypothesis, there is no relationship between 2 categorical variables")

accept null hypothesis, there is no relationship between 2 categorical variables
